events {}

http {
    upstream node_backend {
        server startup-node-app:3000;
    }

    # LOCALHOST (HTTP only)
    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://node_backend;
            proxy_set_header Host $host;
        }
    }

    # DOMAIN HTTP → HTTPS
    server {
        listen 80;
        server_name soumomukherjee.tech www.soumomukherjee.tech;
        return 301 https://$host$request_uri;
    }

    # DOMAIN HTTPS
    server {
        listen 443 ssl;
        server_name soumomukherjee.tech www.soumomukherjee.tech;

        ssl_certificate     /etc/ssl/certs/cloudflare.pem;
        ssl_certificate_key /etc/ssl/private/cloudflare.key;


        location / {
            proxy_pass http://node_backend;
            proxy_set_header Host $host;
        }
    }
}
